### ISSUE TITLE
When parsing an Operation object, swagger-parser requires the optional 'tags' field

### ISSUE THREAD

**Issue by zdelagrange** [Trax-air/swagger-parser#12]
See the stack trace below. When trying to parse an Operation object, swagger-parser requires there to be a non-empty tag field associated with it. Since the tag field is optional, the parser should handle the tag field either being empty or non-existent.

`  File "local/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 72, in __init__
    self.get_paths_data()
  File "local/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 363, in get_paths_data
    self.operation[path_spec[action]['operationId']] = (path, action, path_spec[action]['tags'][0])
IndexError: list index out of range`

**Comment by traxair** [comment]
Seems pretty straightforward, how do you feel about submitting a pull request to fix this particular issue?

**Comment by zdelagrange** [comment]
Will make a fork in the next few days and submit one. Didn't have time
today, but I wanted to at least add an issue.

**Comment by traxair** [comment]
Great, we'll include that in the next release then! Which one of our other libraries do you use this one with if I may be curious?

**Comment by zdelagrange** [comment]
Just started taking a look at swagger testing today. We have a few swagger apis and started thinking about testing at scale without much overhead, and this seems to be a good start at that.

**Comment by traxair** [comment]
If you come across missing features, let us know 😉
