### ISSUE TITLE
TypeError if there are multiple possible field types

### ISSUE THREAD

**Issue by gergelypolonkai** [Trax-air/swagger-parser#14]
I have an object property like this in my Swagger file:

    "parent": {
        "type": [
            "string",
            "null"
        ]
    }

When parsing the file, I get:

      File "/home/polesz/Projects/python/swagger_validate/venv/local/lib/python2.7/site-packages/swagger_parser/swagger_parser.py", line 165, in get_example_from_prop_spec
        return self._get_example_from_basic_type(prop_spec['type'])[0]
    TypeError: 'NoneType' object has no attribute '__getitem__'

I can circumvent it by setting an explicit `"example"` field, but I think this is a bug.

**Comment by cyprieng** [comment]
Hi, thanks for reporting, but I am not sure array in type is valid in a Swagger file: `Required. The type of the object. The value MUST be one of "string", "number", "integer", "boolean", or "array".` from the swagger specification.

**Comment by gergelypolonkai** [comment]
That’s strange, because the Swagger Editor reports it as valid.

**Comment by cyprieng** [comment]
Ok, In this case I will make a fix.
