### ISSUE TITLE
Parser assumes `properties` key always exists in a given swagger definition

### ISSUE THREAD

**Issue by SalimBensiali** [Trax-air/swagger-parser#35]
But definitions of type array for example do not have a `properties` key. see [swagger_parser.py#L483](https://github.com/Trax-air/swagger-parser/blob/master/swagger_parser/swagger_parser.py#L483)

Cheers.

**Comment by cyprieng** [comment]
Yes you are right, if you want to provide a fix you are welcome, or I can do it :smile:

**Comment by SalimBensiali** [comment]
Thanks. I have a fix on my fork, but I am not sure where a test for this should go. Any insights?
